server:
  port: 80
security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aceace?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: 12345678
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates

#mybatis config
mybatis:
  mapper-locations: classpath:/mapper/*.xml